version: "3.8"
services:
  python:
    build: .
    environment: &TZ
      - TZ=Asia/Taipei

  selenium-standalone:
    image: selenium/standalone-chrome:3.11.0
    ports:
      - "4444:4444"
    environment: *TZ


